# Preface

The purpose of these notes is to provide students of ACCT 90012 *Corporate Reporting* with a replacement for problematic materials in the course text book, *Financial Reporting* (fourth edition).

The following portions of *Financial Reporting* can be read profitably in conjunction with these materials:^[Readers of the third edition of *Financial Reporting* will need to adjust the chapter numbers, which are generally one chapter earlier there than in the fourth edition.]

 - Chapter 26: Business combinations
 - Chapter 27: Consolidation: controlled entities
 - Chapter 29: Consolidation: intragroup transactions *except for* the demonstration problem
 - Chapter 31: Consolidation: other issues
 - Chapter 32: Associates and joint ventures
 
However, the following portions of *Financial Reporting* use approaches inconsistent with these materials and should be avoided or only read by students alert to the inconsistencies.

 - Chapter 28: Consolidation: wholly owned entities
 - The demonstration problem in Chapter 29
 - Chapter 30: Consolidation: non-controlling interest
 
 The reason for replacing these materials is that they provide a confusing approach to the business combination valuation reserve (BCVR).
The approach to BCVR in *Financial Reporting* has two problems.

First, treatment of BCVR is not consistent across chapters.
For example, BCVR includes goodwill in Chapter 28, but excludes goodwill in Chapter 30 when the partial goodwill method is applied.
In the latter case, goodwill is included in the pre-acquisition entry.
In contrast, these materials always include goodwill in the pre-acquisition entry.

Second, the amount of BCVR varies from one period to the next.
In *Financial Reporting*, so revaluation adjustments are moved to the pre-acquisition entry as the associated assets are consumed, even though the total amount of revaluation is unaffected.
As a result, the pre-acquisition entry in *Financial Reporting* needs to change in each period as revaluations are shifted to that entry.
In contrast, in these materials the amount of revaluation reflected in BCVR does not change (putting aside measurement period adjustments) after the acquisition date.
Similarly, the pre-acquisition elimination entry also remains the same in each period.

Interested students seeking a more comprehensive set of materials used here should note that some textbooks provide a presentation of consolidation accounting consistent with that used in these materials.
For example, *Accounting for Corporate Combinations and Associations* (eighth edition) by Neal Arthur, Louise Luff, Peter Keet, Matthew Egan, Bryan Howieson, and Ronita Ram treats BCVR much as we do in these materials.^[The term "BCVR" is not used in *Accounting for Corporate Combinations and Associations*, which instead calls it "fair value adjustment".]