# Non-controlling interest {#sec-nci}

NCI arises when entities other than the parent entity own shares in members of the group (other than the parent).
NCI is defined in Appendix A of AASB 10 (IFRS 10) *Consolidated Financial Statements* as "equity in a subsidiary not attributable, directly or indirectly, to a parent."
Typically NCI will represent a minority interest in a subsidiary that is controlled by the parent (directly or indirectly) through a majority interest.
In general the existence of NCI does not affect the processes of preparing consolidated accounts at a group level.
Rather NCI is part of the presentation of group equity as comprising the interest of shareholders in the parent and NCI.

NCI at time of acquisition may be measured in either of two ways:
 - NCI’s proportionate share of the acquiree’s net assets
 - Fair value of NCI
Under the first method, there is no goodwill associated with NCI. 
Goodwill will be the difference between the purchase consideration paid by the parent and the parent’s proportionate share of the fair value of identifiable net assets (FVINA).
This is the **partial goodwill method**.

Under the second method, goodwill will be the difference between the purchase consideration paid by the parent and the parent's proportionate share of FVINA plus the difference between the fair value of NCI and the NCI's proportionate share of FVINA. 
This is the **full goodwill method**.
Both methods allowed under *AASB3 Business combinations*.
In some cases, it can be costly to measure NCI fair value.
But NCI can be measured easily in some cases, such as when the subsidiary is publicly traded.
*We focus on the partial goodwill method in ACCT 90012.*

From the perspective of the subsidiary, NCIs have an interest in the subsidiary's profit and net assets.
However, from the perspective of the group, NCIs have an interest in the *subsidiary's contribution* to the group's profit and net assets.

## NCI: Steps

NCI's share of equity at the end of the current period can be partitioned into three components, which can be viewed as three *steps*.

  1. Share of equity recorded at acquisition date
  2. Share of change in equity from acquisition date to beginning of current period
  3. Share of change in equity in the current period
  
Accounting for each of these components can be viewed as a step in the preparation of NCI.

## Consolidation with NCI

Fair value increments are applied to identifiable net assets, which are unaffected by the existence of NCI.
Thus, the BCVR entry is unaffected by NCI.
However, offsets to BCVR---typically debits---can affect Step 2 and Step 3 elements of NCI.

With NCI, the elimination entry is applied in two parts.
First, we eliminate the parent's interest in pre-acquisition equity.
Second, we eliminate the NCI in pre-acquisition equity; this is Step 1.

The remaining group consolidation entries are largely unaffected.
However, each consolidation entry we make needs be examined for effects on beginning-of-period NCI (Step 2) and current period changes in NCI (Step 3).

In the presentation in this chapter, the consolidation worksheet is expanded to include a section for NCI.
The NCI portion of the worksheet functions much like group portion introduced in previous chapters.

## Comprehensive example

On 1 July 2013, Parent Ltd acquired control of Subsidiary Ltd by purchasing 80% of its share capital  for $300,000. At this date, the equity of Subsidiary Ltd was:

| | |
|------|------:|
| Share capital     |  $130,000 |
| General reserve   | 70,000 |
| Retained earnings | 50,000 |

All the identifiable assets and liabilities were recorded at FV except for the following:

| | CA | FV |
|------|------:|------:|
| Inventory | 80,000 | 90,000 |
| Plant (cost $160,000) | 130,000 | 180,000 |
| Land | 60,000 | 120,000 |

The plant had a remaining useful life of 10 years, with benefits to be received evenly over this period.

All the inventory on hand at 1 July 2013 was sold by 30 June 2014.
Subsidiary Ltd made a profit of \$40,000 for the year ended 30 June 2014. 
No other changes occurred in equity.

At 1 July 2016, there was \$15,000 profit in the inventories of Parent Ltd from goods acquired from Subsidiary Ltd for \$45,000.

During the year ended 30 June 2017, Subsidiary Ltd sold inventory costing $15,000 to Parent Ltd for \$30,000. 
On 30 June 2017, \$6,000 of inventory was still on hand in Parent's books.

On 1 April 2017, Subsidiary Ltd sold an item of plant with a carrying amount of \$40,000 (cost \$160,000, accumulated depreciation \$120,000) to Parent Ltd for \$60,000.
The item was still on hand at the end of the year.
Parent Ltd applied a 20% depreciation rate to this type of plant.

**Required**

1. Prepare the acquisition analysis at acquisition date
2. Prepare the consolidation worksheet entries at acquisition date
3. Prepare the consolidation worksheet entries for year ended 30 June 2014
4. Prepare the consolidation worksheet entries for year ended 30 June 2017
5. Prepare the consolidated financial statements for year ended 30 June 2017

*1. Prepare the acquisition analysis at acquisition date*

|                                 |           |   |
|---------------------------------|----------:|---|
| Share capital                   | 130 000   |   |
| General reserve                 | 70 000    | + |
| Retained earnings - beginning   | 50 000    | + |
| BCVR                            | 84 000    | + |
| **FVINA**                       |**334 000**| = |
|                                 |           |   |
| Parent's purchase consideration | 300 000   |   |
| NCI (20\% of 334,000)           | 66 800    | + |
| **FV of business acquired**     |**366 800**| = |
|                                 |           |   |
| FV of business acquired         | 366 800   |   |
| FVINA                           | 334 000   | --|
| **Goodwill**                    |**32 800** | = |

*2. Prepare the consolidation worksheet entries at acquisition date*

(1) BCVR entry

|                                  |  Debit | Credit |
|----------------------------------|-------:|-------:|
| Acc. dep. -- Plant and equipment | 30 000 |        |
| Plant                            | 20 000 |        |
|  Deferred tax liability          |        | 15 000 |
|  BCVR                            |        | 35 000 |
|                                  |        |        |
| Inventory                        | 10 000 |        |
|  Deferred tax liability          |        |  3 000 |
|  BCVR                            |        |  7 000 |
|                                  |        |        |
| Land                             | 60 000 |        |
|  Deferred tax liability          |        | 18 000 |
|  BCVR                            |        | 42 000 |

Total BCVR = \$35,000 + 7,000 + 42,000 = \$84,000.

(2) Elimination of investment in subsidiary

|                                 |  Debit  |  Credit |
|---------------------------------|--------:|--------:|
| Share capital                   | 130 000 |         |
| General reserve	                |  70 000 |         |
| Retained earnings - beginning   |  50 000 |         |
| BCVR                            |  84 000 |         |
| Goodwill                        |  32 800 |         |
| Shares in Subsidiary		        |         | 300 000 |
|	NCI	                            |         |  66 800 |

We can analyse this entry into an entry related to the parent and an entry related to NCI.

The *parent* entry includes 80\% of the non-goodwill elements and *all* of the goodwill.

|                                 |  Debit  |  Credit |
|---------------------------------|--------:|--------:|
| Share capital                   | 104 000 |         |
| General reserve	                |  56 000 |         |
| Retained earnings - beginning   |  40 000 |         |
| BCVR                            |  67 200 |         |
| Goodwill                        |  32 800 |         |
| Shares in Subsidiary		        |         | 300 000 |

The *NCI* entry includes 20\% of the non-goodwill elements and *none* of the goodwill.

|                                 |  Debit  |  Credit |
|---------------------------------|--------:|--------:|
| Share capital                   |  26 000 |         |
| General reserve	                |  14 000 |         |
| Retained earnings - beginning   |  10 000 |         |
| BCVR                            |  16 800 |         |
|	NCI	                            |         |  66 800 |

*3. Prepare the consolidation worksheet entries for year ended 30 June 2014*

 - All the inventory on hand at 1 July 2013 was sold by 30 June 2014.
 - Acquired plant had a remaining useful life of 10 years, with benefits to be received evenly over this period.
 - Subsidiary Ltd made a profit of \$40,000 for the year ended 30 June 2014. No other changes occurred in equity.

(1) BCVR entry

After one year, the fair value increments associated with inventory and plant will have been wholly (inventory) or partly (plant) realised as expenses.
While the principles are the same for these two items, we will do what we did in @sec-wholly-owned and take slightly different approaches to these two items.

For plant, we reiterate the BCVR entry made at acquisition, but we now supplement it with an entry to recognise depreciation for the year.
With a fair value increment of \$50,000 and remaining useful life of 10 years, we have annual depreciation (of the fair value increment) of \$5,000.

Of course, an additional expense of \$5,000 implies a reduction of income tax expense of \$1,500.
This is applied to the deferred tax liability created in the acquisition-date BCVR entry.

As the inventory was all sold in the first year, we need to debit *Cost of sales* rather than *Inventory*.
This additional expense upon consolidation of \$10,000 implies a reduction of income tax expense of \$3,000.
As always, the credit to BCVR for inventory remains at its original \$7,000.

Because nothing has happened to land since acquisition, the associated BCVR entry is unchanged.

|                                  |  Debit | Credit |
|----------------------------------|-------:|-------:|
| Acc. dep. -- Plant               | 30 000 |        |
| Plant                            | 20 000 |        |
|  Deferred tax liability          |        | 15 000 |
|  BCVR                            |        | 35 000 |
|                                  |        |        |
| Depreciation expense             |  5 000 |        |
|  Acc. dep. -- Plant              |        |  5 000 |
|                                  |        |        |
| Deferred tax liability           |  1 500 |        |
|  Income tax expense              |        |  1 500 |
|                                  |        |        |
| Cost of sales                    | 10 000 |        |
|  Income tax expense              |        |  3 000 |
|  BCVR                            |        |  7 000 |
|                                  |        |        |
| Land                             | 60 000 |        |
|  Deferred tax liability          |        | 18 000 |
|  BCVR                            |        | 42 000 |

(2) Elimination of investment in subsidiary

This entry is unchanged from that made at acquisition (see above).
Here we just reiterate the portion related to the parent's investment in the subsidiary.

|                                 |  Debit  |  Credit |
|---------------------------------|--------:|--------:|
| Share capital                   | 104 000 |         |
| General reserve	                |  56 000 |         |
| Retained earnings - beginning   |  40 000 |         |
| BCVR                            |  67 200 |         |
| Goodwill                        |  32 800 |         |
|  Shares in Subsidiary		        |         | 300 000 |

We now prepare the entries related to NCI.
Because the acquisition was made at the start of the current period, there is not "Step 2" here (i.e., there are not changes in NCI between acquisition date and the start of the current period).

We start by analysing the consolidation entries above for possible effects on NCI.

(1') BCVR entry--NCI

Because the acquisition-date entry for BCVR applies to the group, there is no separate entry for NCI for that portion (Step 1).

However, the BCVR entry we made above also relates to Step 3 because there are effects on current-period income.
The effects on group income are all connected with the subsidiary in which NCI relates.
These effects are:
  
  - --5,000 (depreciation expense) +1,500 (income tax expense)
  - --10,000 (cost of sales) +3,000 (income tax expense)
  
Thus the total effect is --10,500, of which 2,100 ($20\% \times -10500$) relates to NCI.

|                                  |  Debit | Credit |
|----------------------------------|-------:|-------:|
| NCI                              |  2 100 |        |
|  NCI share of profit             |        |  2 100 |
 
(2') Elimination of NCI at acquisition

We saw the following entry above.

|                                 |  Debit  |  Credit |
|---------------------------------|--------:|--------:|
| Share capital                   |  26 000 |         |
| General reserve	                |  14 000 |         |
| Retained earnings - beginning   |  10 000 |         |
| BCVR                            |  16 800 |         |
|	NCI	                            |         |  66 800 |

(3') Recognition of NCI share of change in equity

The entries above relate to consolidation entries.
However, we also need to account for the NCI share of changes in the *reported* equity in the current period.
We are told above that the only change in the equity of the subsidiary is a profit of \$40,000.
Of this, \$8,000 ($20\% \times 40000$) is attributable to NCI.

|                                  |  Debit | Credit |
|----------------------------------|-------:|-------:|
| NCI share of profit              |  8 000 |        |
|  NCI                             |        |  8 000 |

*4. Prepare the consolidation worksheet entries for year ended 30 June 2017*

 - At 1 July 2016, there was \$15,000 profit in the inventories of Parent Ltd Ltd from goods acquired from Subsidiary Ltd for \$45,000.
 - During the year ended 30 June 2017, Subsidiary Ltd sold inventory costing \$15,000 to Parent Ltd for \$30,000.
On 30 June 2017, \$6,000 of inventory was still on hand in Parent's books.
 - On 1 April 2017, Subsidiary Ltd sold an item of plant with a carrying amount of \$40,000 (cost \$160,000, accumulated depreciation \$120,000) to Parent Ltd for \$60,000.
The item was still on hand at the end of the year. Parent Ltd applied a 20\% depreciation rate to this type of plant.


(1) BCVR entry

We can use our BCVR entry for the previous answer as a template..

Again, we reiterate the BCVR entry made at acquisition for plant, but we now supplement it with an entry to recognise depreciation since acquisition.
With annual depreciation of the fair value increment of \$5,000, we have three years prior to this year plus this year's depreciation (\$15,000).
These imply a reduction of income tax expense of \$1,500 in the current period and \$4,500 in previous periods (now in *Retained earnings--beginning*)
The tax amounts are applied to the deferred tax liability created in the acquisition-date BCVR entry.

As the inventory was all sold in the first year, the debit is entirely to *Retained earnings--beginning*. 

Because nothing has happened to land since acquisition, the associated BCVR entry is unchanged.

|                                  |  Debit | Credit |
|----------------------------------|-------:|-------:|
| Acc. dep. -- Plant               | 30 000 |        |
| Plant                            | 20 000 |        |
|  Deferred tax liability          |        | 15 000 |
|  BCVR                            |        | 35 000 |
|                                  |        |        |
| Retained earnings--beginning     | 15 000 |        |
| Depreciation expense             |  5 000 |        |
|  Acc. dep. -- Plant              |        | 20 000 |
|                                  |        |        |
| Deferred tax liability           |  6 000 |        |
|  Income tax expense              |        |  1 500 |
|  Retained earnings--beginning    |        |  4 500 |
|                                  |        |        |
| Retained earnings--beginning     |  7 000 |        |
|  BCVR                            |        |  7 000 |
|                                  |        |        |
| Land                             | 60 000 |        |
|  Deferred tax liability          |        | 18 000 |
|  BCVR                            |        | 42 000 |

(2) Elimination of investment in subsidiary

This entry is unchanged from that made at acquisition (see above).

(3) Reversal of sales -- realised

As discussed in @sec-intragroup, for the elimination of intragroup sales of inventory in the current period, we can prepare separate consolidation journal entries for the realised and unrealised portions.
As we saw in @sec-intragroup, the realised sales require a simple elimination against sales and cost of sales for the amount of intragroup sales realised as external sales ($30000 - 6000$).

|                                  |  Debit | Credit |
|----------------------------------|-------:|-------:|
| Sales                            | 24 000 |        |
|  Cost of sales                   |        | 24 000 |

(4) Reversal of sales -- unrealised

The remaining inventory in shown in the books of Parent at \$6,000.
The original cost for this inventory was \$3,000 ($15000 \div 30000 \times 6000$).
Thus we have \$3,000 in unrealised profit in inventory, which requires the  entry below.
Eliminating this profit means reducing income tax expense by \$900 ($30\% \times 3000$).
This reduction gives rise to a deferred tax asset (intuitively, we need to debit *something* to balance the credit to *Income tax expense*).

|                                  |  Debit | Credit |
|----------------------------------|-------:|-------:|
| Sales                            |  6 000 |        |
|  Cost of sales                   |        |  3 000 |
|  Inventory                       |        |  3 000 |
|                                  |        |        |
| Deferred tax asset               |    900 |        |
|  Income tax expense              |        |    900 |
