<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Course materials for consolidations module of Corporate Reporting">

<title>Consolidation accounting - 6&nbsp; Accounting for associates</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./nci.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./equity.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Accounting for associates</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Consolidation accounting</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bus-combs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Business combinations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./wholly-owned.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Consolidation: Wholly owned entities</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intragroup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Consolidation: Intragroup transactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nci.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Non-controlling interest</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./equity.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Accounting for associates</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#equity-method-of-accounting" id="toc-equity-method-of-accounting" class="nav-link active" data-scroll-target="#equity-method-of-accounting"><span class="header-section-number">6.1</span> Equity method of accounting</a>
  <ul class="collapse">
  <li><a href="#elimination-of-inter-entity-transactions" id="toc-elimination-of-inter-entity-transactions" class="nav-link" data-scroll-target="#elimination-of-inter-entity-transactions"><span class="header-section-number">6.1.1</span> Elimination of inter-entity transactions</a></li>
  </ul></li>
  <li><a href="#equity-accounting-abe-ltd-and-jason-ltd" id="toc-equity-accounting-abe-ltd-and-jason-ltd" class="nav-link" data-scroll-target="#equity-accounting-abe-ltd-and-jason-ltd"><span class="header-section-number">6.2</span> Equity accounting: Abe Ltd and Jason Ltd</a>
  <ul class="collapse">
  <li><a href="#equity-accounting-when-investor-prepares-consolidated-accounts" id="toc-equity-accounting-when-investor-prepares-consolidated-accounts" class="nav-link" data-scroll-target="#equity-accounting-when-investor-prepares-consolidated-accounts"><span class="header-section-number">6.2.1</span> Equity accounting when investor prepares consolidated accounts</a></li>
  <li><a href="#equity-accounting-in-books-of-investor" id="toc-equity-accounting-in-books-of-investor" class="nav-link" data-scroll-target="#equity-accounting-in-books-of-investor"><span class="header-section-number">6.2.2</span> Equity accounting in books of investor</a></li>
  </ul></li>
  <li><a href="#applied-issues" id="toc-applied-issues" class="nav-link" data-scroll-target="#applied-issues"><span class="header-section-number">6.3</span> Applied issues</a>
  <ul class="collapse">
  <li><a href="#impairment-of-investments-in-associates" id="toc-impairment-of-investments-in-associates" class="nav-link" data-scroll-target="#impairment-of-investments-in-associates"><span class="header-section-number">6.3.1</span> Impairment of investments in associates</a></li>
  <li><a href="#losses-of-associates" id="toc-losses-of-associates" class="nav-link" data-scroll-target="#losses-of-associates"><span class="header-section-number">6.3.2</span> Losses of associates</a></li>
  <li><a href="#disclosure-requirements" id="toc-disclosure-requirements" class="nav-link" data-scroll-target="#disclosure-requirements"><span class="header-section-number">6.3.3</span> Disclosure requirements</a></li>
  </ul></li>
  <li><a href="#control-versus-significant-influence" id="toc-control-versus-significant-influence" class="nav-link" data-scroll-target="#control-versus-significant-influence"><span class="header-section-number">6.4</span> Control versus significant influence</a>
  <ul class="collapse">
  <li><a href="#control" id="toc-control" class="nav-link" data-scroll-target="#control"><span class="header-section-number">6.4.1</span> Control</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-associates" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Accounting for associates</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>An associate is an entity over which the investor has <strong>significant influence</strong> (Para 3 AASB 128). Significant influence is the power to participate in the financial and operating policy decisions of the investee, but is not control or joint control over those policies.</p>
<p>Judgement required in determining the existence of significant influence and AASB 128 provides guidance. Significant influence is <em>presumed</em> to exist if an entity holds, directly or indirectly, 20% or more of the voting power of the investee unless it can be clearly demonstrated that this is not the case (e.g., another entity holds more than 50%). Other factors that can indicate significant influence include:</p>
<ul>
<li>Representation on the board of directors or equivalent governing body of the investee</li>
<li>Participation in policy-making processes including participation in decisions about dividends</li>
<li>Material transactions between the entity and its investee</li>
<li>Interchange of managerial personnel or provision of essential technical information</li>
</ul>
<section id="equity-method-of-accounting" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="equity-method-of-accounting"><span class="header-section-number">6.1</span> Equity method of accounting</h2>
<p>The equity method of accounting, also referred to as <em>one-line consolidation</em>, accounts for an investment in an associate as investor’s the share of the (adjusted) equity of the associate. A single line item in the income statement for investor’s share of profit of current period. A single line item in the balance sheet showing carrying amount of investment in the associate.</p>
<p>Paragraph 10 of AASB 128 (IAS 28) says: “Under the equity method, on initial recognition the investment in an associate or a joint venture is recognised at cost, and the carrying amount is increased or decreased to recognise the investor’s share of the profit or loss of the investee after the date of acquisition. The investor’s share of the investee’s profit or loss is recognised in the investor’s profit or loss. Distributions received from an investee reduce the carrying amount of the investment. Adjustments to the carrying amount may also be necessary for changes in the investor’s proportionate interest in the investee arising from changes in the investee’s other comprehensive income.”</p>
<p>Measurement under the equity method:</p>
<ul>
<li>Recognise the initial investment in the investee at cost</li>
<li>Increase or decrease carrying amount of investment by the investor’s share of the profit or loss (and other comprehensive income)</li>
<li>Income adjusted for intra-company sales and effects of fair-value adjustments at time of acquisition.</li>
<li>Reduce the carrying amount of the investment by dividends received</li>
</ul>
<p>AASB 127 (IAS 27) <em>Separate Financial Statements</em> states that, for entities that prepare consolidated financial statements, investments in subsidiaries, joint ventures and associates are accounted for either at cost or in accordance with AASB 9 (IFRS 9) <em>Financial Instruments</em>. Under the cost method, dividends from associate are treated as dividend revenue. When consolidated financial statements are prepared, the parent converts from the cost method to the equity method. When the investor does not prepare consolidated financial statements, equity accounting is done in the books of the investor.</p>
<section id="elimination-of-inter-entity-transactions" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="elimination-of-inter-entity-transactions"><span class="header-section-number">6.1.1</span> Elimination of inter-entity transactions</h3>
<p>A careful reader will note that paragraph 10 of AASB 128 (IAS 28) says nothing about adjustments to “the profit or loss of the investee” due to transactions between the associate and the investor. Under AASB 10 (IFRS 10), the parent and its subsidiaries for an economic entity and the rationale for eliminating unrealised profits on intragroup transactions is clear. The rationale for eliminating analogous profits on transactions between the associate and the investor is far from clear, as the associate and its investor do not form a single economic entity.</p>
<p>Nonetheless, AASB 128 (IAS 28) provides a number of clues suggesting that such elimination is required. First, paragraph 26 suggests that “many of the procedures that are appropriate for the application of the equity method are similar to the consolidation procedures described in AASB 10.” Second, paragraph 28 says that “gains and losses resulting from ‘upstream’ and ‘downstream’ transactions … between an entity (including its consolidated subsidiaries) and its associate or joint venture are recognised in the entity’s financial statements only to the extent of unrelated investors’ interests in the associate or joint venture.” Implicitly, we can flip this last sentence to conclude that “gains and losses … are <em>eliminated</em> in the entity’s financial statements only to the extent of the <em>affiliated investor’s</em> interests in the associate.”</p>
<p>Parsing these statements may seem daunting, but in practice their requirements are straightforward to apply, as can be seen from two straightforward examples in which Investor owns 20% of Associate.</p>
<p>First, suppose that Investor sells inventory to Associate (i.e., a downstream transaction) at a pre-tax profit of $2,000 and that the tax rate is 30%, giving an after-tax profit of $1,400, and that all of the inventory remains on hand at Associate at the end of the period. Only 20% of the profits need to be eliminated and this can be effected by making an adjustment for the full $1,400 of “inter-entity” profits and then recognizing the 20% of this as part of equity accounting.</p>
<p>Second, suppose that Associate sells inventory to Investor (i.e., an upstream transaction) at a pre-tax profit of $2,000 and that the tax rate is 30%, giving an after-tax profit of $1,400, and that all of the inventory remains on hand at Investor at the end of the period. Only 20% of the profits need to be eliminated and again this can be effected by making an adjustment for the full $1,400 of “inter-entity” profits and then recognizing the 20% of this as part of equity accounting.</p>
<p>While AASB 128 (IAS 28) distinguishes between “upstream” and “downstream” transactions, the accounting is essentially the same.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> That said, it should be noted that in the first case we are adjusting the profit of the associate even though the unrealised profit is entirely on the books of the investor. This approach may seem counter-intuitive, but can be justified on the basis that it delivers the correct results.</p>
</section>
</section>
<section id="equity-accounting-abe-ltd-and-jason-ltd" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="equity-accounting-abe-ltd-and-jason-ltd"><span class="header-section-number">6.2</span> Equity accounting: Abe Ltd and Jason Ltd</h2>
<p>On 1 July 2017, Abe Ltd acquired 30% of the shares of Jason Ltd for $82,000. The directors of Abe Ltd believe that Abe Ltd exerts <em>significant influence</em> over Jason Ltd.&nbsp; All the identifiable assets and liabilities of Jason Ltd at the date of acquisition were recorded in their books at fair value except for plant with a fair value of $20,000 in excess of its carrying amount. The plant is expected to have a further 5 years of useful life.</p>
<div id="tbl-jason-fs" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-jason-fs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Financial statement data for Jason Ltd
</figcaption>
<div aria-describedby="tbl-jason-fs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 46%">
<col style="width: 17%">
<col style="width: 18%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">1 July 2017</th>
<th style="text-align: right;">30 June 2018</th>
<th style="text-align: right;">30 June 2019</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Share capital</td>
<td style="text-align: right;">150 000</td>
<td style="text-align: right;">150 000</td>
<td style="text-align: right;">150 000</td>
</tr>
<tr class="even">
<td>Retained earnings</td>
<td style="text-align: right;">60 000</td>
<td style="text-align: right;">130 000</td>
<td style="text-align: right;">290 000</td>
</tr>
<tr class="odd">
<td>General reserve</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">8 000</td>
<td style="text-align: right;">8 000</td>
</tr>
<tr class="even">
<td>Asset revaluation surplus</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">21 000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Profit before tax</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">117 000</td>
<td style="text-align: right;">300 000</td>
</tr>
<tr class="odd">
<td>Income tax expense</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">33 000</td>
<td style="text-align: right;">85 000</td>
</tr>
<tr class="even">
<td>Profit after tax</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">84 000</td>
<td style="text-align: right;">215 000</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Retaining earnings – beginning</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">60 000</td>
<td style="text-align: right;">130 000</td>
</tr>
<tr class="odd">
<td>Profit after tax</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">84 000</td>
<td style="text-align: right;">215 000</td>
</tr>
<tr class="even">
<td>Dividends paid</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">6 000</td>
<td style="text-align: right;">25 000</td>
</tr>
<tr class="odd">
<td>Dividends declared</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">30 000</td>
</tr>
<tr class="even">
<td>Transfers to general reserve</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">8 000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Retained earnings – ending</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">130 000</td>
<td style="text-align: right;">290 000</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Additional information:</p>
<ol type="1">
<li><p>Abe Ltd recognises dividends as revenue when declared by its investee companies. All dividends are assumed to be paid from current-year profits.</p></li>
<li><p>On 1 January 2018, Jason Ltd sold an item of equipment to Abe Ltd, carrying amount at date of sale was $20,000, for $30,000. Abe Ltd depreciates this equipment at 20% per annum.</p></li>
<li><p>At 30 June 2019, Abe Ltd had unsold inventories costing $50,000 (2018: $80,000) which had been purchased from Jason Ltd. Jason Ltd has recorded a profit before tax of $11,000 (2018: $16,000) in its books for the respective years.</p></li>
<li><p>Jason Ltd recorded an asset revaluation surplus of $21,000 (after tax) in the year ended 30 June 2018 and had no additional revaluation in the year ended 30 June 2019.</p></li>
<li><p>Jason Ltd also transferred $8,000 from retained earnings to general reserve in the year ended 30 June 2018.</p></li>
</ol>
<section id="equity-accounting-when-investor-prepares-consolidated-accounts" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="equity-accounting-when-investor-prepares-consolidated-accounts"><span class="header-section-number">6.2.1</span> Equity accounting when investor prepares consolidated accounts</h3>
<p>For entities that prepare consolidated financial statements under AASB 127 (IAS 27) <em>Separate Financial Statements</em>, investments in subsidiaries, joint ventures and associates re accounted for either at cost or in accordance with AASB 9 (IFRS 9) <em>Financial Instruments</em>. Under the cost method, dividends from associate are treated as dividend revenue in the investor’s separate financial accounts. When consolidated financial statements are prepared, the parent converts from the cost method to the equity method.</p>
<p>In the following analysis, we assume that the Abe is a parent that prepares consolidated financial statements. We can calculate the after-tax amount of the fair value adjustment as $14,000 <span class="math inline">\((20000 \times (1 - 30\%))\)</span>. From the analysis of the investment in <a href="#tbl-jason-aa" class="quarto-xref">Table&nbsp;<span>6.3</span></a>, we see that the FVINA is $224,000.</p>
<p>Abe’s share of FVINA is 20% of $224,000, or $67,200. Given that the cost of the investment to Abe Ltd was $82,000, goodwill is $14,800 <span class="math inline">\((82000 - 67200)\)</span>.</p>
<div id="tbl-jason-aa" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-jason-aa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Acquisition analysis for investment in Jason Ltd
</figcaption>
<div aria-describedby="tbl-jason-aa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<tbody>
<tr class="odd">
<td>Share capital</td>
<td style="text-align: right;">150 000</td>
</tr>
<tr class="even">
<td>Retained earnings</td>
<td style="text-align: right;">60 000</td>
</tr>
<tr class="odd">
<td>Fair value adjustment</td>
<td style="text-align: right;">14 000</td>
</tr>
<tr class="even">
<td>FVINA</td>
<td style="text-align: right;">224 000</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Cost of investment</td>
<td style="text-align: right;">82 000</td>
</tr>
<tr class="odd">
<td>Investor share of FVINA</td>
<td style="text-align: right;">67 200</td>
</tr>
<tr class="even">
<td>Goodwill</td>
<td style="text-align: right;">14 800</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>Adjustment of profit of associate for year ended 30 June 2018</em></p>
<p>The fair value adjustment will be amortised over 5 years, reducing adjusted (after-tax) income of Jason Ltd by $2,800 in each year.</p>
<p>Under AASB 128 (IAS 28) in unrealised gain on the sale of equipment by Jason to Abe is eliminated. The after-tax profit to be eliminated is $7,000.</p>
<p>The additional depreciation related to this gain is also eliminated. As the sale occurred on 1 January 2018, we need to eliminate half a year’s worth of depreciation at a rate of 20%, which is $700 <span class="math inline">\((7000 \times \frac{1}{2} \times 20\%)\)</span>. The unrealised profit in ending inventory is $11,200 <span class="math inline">\((11000 \times (1 - 30\%))\)</span>.</p>
<p>As can be seen in <a href="#tbl-jason-aa" class="quarto-xref">Table&nbsp;<span>6.3</span></a>, these adjustments yield adjusted profit of $63,700 for the year ended 30 June 2018.</p>
<p><em>Adjustment of profit of associate for year ended 30 June 2019</em></p>
<p>Additional depreciation continues as discussed above. The additional depreciation related to the gain on the sale of equipment in the previous year is again eliminated. But we need to eliminate a full year’s worth of depreciation at a rate of 20%, which is $1,400 <span class="math inline">\((7000 \times 20\%)\)</span>.</p>
<p>The unrealised profit in ending inventory is $7,700 <span class="math inline">\((16000 \times (1 - 30\%))\)</span>. The unrealised profit in beginning inventory is realised in the current period. We calculated this above as $11,200.</p>
<p>As can be seen in <a href="#tbl-jason-aa" class="quarto-xref">Table&nbsp;<span>6.3</span></a>, this yields adjusted profit of $217,100 for the year ended 30 June 2019.</p>
<div id="tbl-jason-aa" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-jason-aa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: Adjustment of profit of associate
</figcaption>
<div aria-describedby="tbl-jason-aa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">30 June 2018</th>
<th style="text-align: right;">30 June 2019</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Profit after tax</td>
<td style="text-align: right;">84 000</td>
<td style="text-align: right;">215 000</td>
</tr>
<tr class="even">
<td>Additional depreciation</td>
<td style="text-align: right;">(2 800)</td>
<td style="text-align: right;">(2 800)</td>
</tr>
<tr class="odd">
<td>Unrealised profit on sale of equipment</td>
<td style="text-align: right;">(7 000)</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Realised profit through depreciation</td>
<td style="text-align: right;">700</td>
<td style="text-align: right;">1 400</td>
</tr>
<tr class="odd">
<td>Unrealised profit in closing inventory</td>
<td style="text-align: right;">(11 200)</td>
<td style="text-align: right;">(7 700)</td>
</tr>
<tr class="even">
<td>Unrealised profit in opening inventory</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">11 200</td>
</tr>
<tr class="odd">
<td><strong>Adjusted profit after tax</strong></td>
<td style="text-align: right;"><strong>63 700</strong></td>
<td style="text-align: right;"><strong>217 100</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>Journal entries in books of investor for year ended 30 June 2018</em></p>
<p>It is helpful to consider first the journal entries related to the associate (Jason Ltd) that would be made in the books of the investor (Abe Ltd). We start with the year ended 30 June 2018, which is the year of investment.</p>
<p>The first entry would be made on the purchase of the stake in Jason Ltd.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Investment in associate</td>
<td style="text-align: right;">82 000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Cash</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">82 000</td>
</tr>
</tbody>
</table>
<p>Later, Abe would recognize the dividends paid by Jason as revenue.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cash</td>
<td style="text-align: right;">1 800</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Dividend revenue</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1 800</td>
</tr>
</tbody>
</table>
<p><em>Consolidation journal entries for year ended 30 June 2018</em></p>
<p>Now, we consider the equity journal entries that would be made. These might part of the process of preparing consolidation journal entries.</p>
<p>First, we reclassify the dividend received from revenue to a reduction in the investment asset.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dividend revenue</td>
<td style="text-align: right;">1 800</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Investment in associate</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1 800</td>
</tr>
</tbody>
</table>
<p>Second, we recognise the investor’s share of the adjusted profit of the associate: <span class="math inline">\(30\% \times 63{\small,}700 = 19{\small,}110\)</span>.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Investment in associate</td>
<td style="text-align: right;">19 110</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Share of profit of associate</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">19 110</td>
</tr>
</tbody>
</table>
<p>Third, we recognise the investor’s share of the other comprehensive income (OCI) of the associate: <span class="math inline">\(30\% \times 21{\small,}000 = 6{\small,}300\)</span>.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Investment in associate</td>
<td style="text-align: right;">6 300</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Gain on revaluation (OCI)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">6 300</td>
</tr>
</tbody>
</table>
<p><em>Journal entries in books of investor for year ended 30 June 2019</em></p>
<p>Abe would recognize the both the dividends paid and the dividends declared by Jason as revenue</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cash</td>
<td style="text-align: right;">7 500</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Dividend revenue</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">7 500</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Dividends receivable</td>
<td style="text-align: right;">9 000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td> Dividend revenue</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">9 000</td>
</tr>
</tbody>
</table>
<p><em>Consolidation journal entries for year ended 30 June 2019</em></p>
<p>First, we reclassify the dividends on consolidation.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dividend revenue</td>
<td style="text-align: right;">7 500</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Investment in associate</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">7 500</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Dividend revenue</td>
<td style="text-align: right;">9 000</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td> Investment in associate</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">9 000</td>
</tr>
</tbody>
</table>
<p>Second, we recognise the investor’s share of the adjusted profit of the associate: <span class="math inline">\(30\% \times 217{\small,}100 = 65{\small,}130\)</span>.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Investment in associate</td>
<td style="text-align: right;">65 130</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Share of profit of associate</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">65 130</td>
</tr>
</tbody>
</table>
<p>Much like we saw in <a href="wholly-owned.html" class="quarto-xref"><span>Chapter 3</span></a>, consolidation journals have no automatic memory, so we need to recognise cumulative changes in retained earnings from prior periods. In this case, we have one prior period in which income was $19,110 and dividends were $1,800, which nets to $17,310. We also make a similar adjustment for cumulative OCI (AOCI).</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Investment in associate</td>
<td style="text-align: right;">17 310</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Retained earnings – beginning</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">17 310</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Investment in associate</td>
<td style="text-align: right;">6 300</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td> AOCI – beginning AOCI</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">6 300</td>
</tr>
</tbody>
</table>
<p>Casual inspection of the entries above in the books of the investor (Abe Ltd) is enough to reveal that, apart from the initial entry, none of the entries affect the account <em>Investment in associate</em>. Thus this account has a value of $82,000 at the end of both fiscal 2018 and fiscal 2019.</p>
<p>In contrast, the value of <em>Investment in associate</em> in the consolidated accounts of the Abe Ltd group is $105,610 at the end of fiscal 2018 and $154,240 at the end of fiscal 2019.</p>
<p>A spreadsheet with the calculations above can be found <a href="https://go.unimelb.edu.au/55d8">here</a>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</section>
<section id="equity-accounting-in-books-of-investor" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="equity-accounting-in-books-of-investor"><span class="header-section-number">6.2.2</span> Equity accounting in books of investor</h3>
<p>As discussed above, when the investor does not prepare consolidated financial statements, AASB 127 (IAS 27) <em>Separate Financial Statements</em> requires that equity accounting be done in the books of the investor. A spreadsheet applying equity accounting in the books of Abe Ltd under the assumption that it does not prepare consolidated financial statements can be found <a href="https://go.unimelb.edu.au/55d8">here</a>.</p>
</section>
</section>
<section id="applied-issues" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="applied-issues"><span class="header-section-number">6.3</span> Applied issues</h2>
<section id="impairment-of-investments-in-associates" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="impairment-of-investments-in-associates"><span class="header-section-number">6.3.1</span> Impairment of investments in associates</h3>
<p>Para 40: If carrying amount exceeds the recoverable amount, then an impairment loss must be recognised</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Debit</th>
<th style="text-align: right;">Credit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Impairment loss</td>
<td style="text-align: right;">XXX</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td> Investment in associate</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">XXX</td>
</tr>
</tbody>
</table>
<p>Because goodwill related to investment in an associate is not separately recognised, it is not tested for impairment separately under AASB 136 (IAS 36) <em>Impairment of Assets</em> (paragraph 42). Instead, the entire carrying amount of the investment is tested for impairment as a single asset. Any impairment loss recognised is not allocated to any asset, including goodwill, that forms part of the carrying amount of the net investment in the associate.</p>
</section>
<section id="losses-of-associates" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="losses-of-associates"><span class="header-section-number">6.3.2</span> Losses of associates</h3>
<p>Under the equity method, losses decrease the carrying amount of the investment in associate. Paragraph 38 of AASB 128 (IAS 28) says that “if an entity’s share of losses of an associate … equals or exceeds its interest in the associate.” This means an investor cannot have a negative investment, which is appropriate if limited liability applies.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Paragraph 39 of AASB 128 (IAS 28) prescribes that “If the associate or joint venture subsequently reports profits, the entity resumes recognising its share of those profits only after its share of the profits equals the share of losses not recognised.”</p>
</section>
<section id="disclosure-requirements" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="disclosure-requirements"><span class="header-section-number">6.3.3</span> Disclosure requirements</h3>
<p>AASB 128 (IAS 28) requires an entity with associated to disclose information that enables users of its financial statements to evaluate</p>
<ul>
<li>The nature, extent and financial effects of its interests in associates</li>
<li>The nature of, and changes in the risks associated with its interest in associates</li>
<li>The nature of the associate and principal place of business</li>
<li>The nature of the relationship (e.g.&nbsp;the nature of the associate’s activities and whether they are strategic to the entity’s activities)</li>
<li>Proportion of ownership and voting rights</li>
<li>Fair value of the investment</li>
<li>Share of any contingent liabilities of the associate</li>
<li>Summarised financial information (aggregated amounts of assets, liabilities, revenues &amp; profit or loss)</li>
<li>Explanations for why 20% or more voting control was not deemed to give significant influence (or why deemed the entity is deemed to have significant influence with less than 20% voting control)</li>
<li>Investor’s share of profits or losses in such associates, the carrying amount of those investments, and the investor’s share of discontinued operations of such associates shall be separately disclosed</li>
<li>Unrecognised share of losses</li>
</ul>
</section>
</section>
<section id="control-versus-significant-influence" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="control-versus-significant-influence"><span class="header-section-number">6.4</span> Control versus significant influence</h2>
<div id="fig-control-sig-infl" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-control-sig-infl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/control-sig-infl.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-control-sig-infl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Control versus significant influence
</figcaption>
</figure>
</div>
<section id="control" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="control"><span class="header-section-number">6.4.1</span> Control</h3>
<ul>
<li>Power over the investee – that is, rights that give it the ability to direct activities that significantly affect the investee’s returns</li>
<li>Exposure to, or rights to, variable returns from its involvement with the investee; and</li>
<li>The ability to use its power over the investee to affect the amount of the investor’s returns</li>
</ul>
<p>The third element above provides the link between the first two elements.</p>
<p>Power arises from substantive rights including voting rights. Holding more than 50% of voting rights, whether directly or indirectly, normally gives power to the investor. If the investors share of voting rights is less than 50%, we need to examine the potential actions of the other shareholders.</p>
<p>In evaluating power, one must consider potential voting rights and whether those potential rights are substantial. To help analyse these issues, PwC provides the flowchart seen in <a href="#fig-sub-rights" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p><strong>Power</strong> includes the right to appoint, reassign or remove key management personnel, right to appoint or remove another entity that participates in management decisions, right to direct the investee to enter into, or block any changes, to transactions that affect the investee’s returns.</p>
<p>Power can be gained via:</p>
<ul>
<li>Ownership of the largest block of voting rights in a situation where the remaining rights are widely dispersed (<strong>de facto control</strong>) (B42-B45)</li>
<li>Potential voting rights (must be substantive) (B47)</li>
<li>Contractual arrangements with other vote holders (B39) or other rights (B40)</li>
<li>A combination of the above</li>
</ul>
<p>De facto control may arise because the investor has the power to unilaterally direct the investee unless a sufficient number of dispersed investors act together. Such coordination may be difficult to organise if doing so requires a large number of investors.</p>
<div id="fig-sub-rights" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sub-rights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/sub_rights.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sub-rights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Flowchart for determining where rights are substantive
</figcaption>
</figure>
</div>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>I say “essentially” because the ellipsis in the quote of paragraph 28 above stands in for the words “involving assets that do not constitute a business, as defined in AASB 3”. Paragraph 31A holds that “the gain or loss resulting from a downstream transaction involving assets that constitute a business, as defined in AASB 3, between an entity (including its consolidated subsidiaries) and its associate or joint venture is recognised in full in the investor’s financial statements.”<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>If you want to change the numbers and you are logged into Google, then you could select <code>File</code> then <code>Make a copy</code> from the menu to make a copy. Alternatively, you could select <code>File</code> then <code>Download</code> to get a version in a format that works for you.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Paragraph 39 suggests that “to the extent that the entity has incurred legal or constructive obligations or made payments on behalf of the associate”, additional losses may be appropriate.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>See <a href="https://www.pwc.com/ng/en/assets/pdf/combined-and-carved-out-financial-statements.pdf">here</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/iangow\.github\.io\/consol");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./nci.html" class="pagination-link" aria-label="Non-controlling interest">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Non-controlling interest</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>